### ISSUE TITLE
Nothing happens when I paste the CCD contents and the "Input document" button doesn't work.

### ISSUE THREAD

**Issue by ScottBeeson** [brynlewis/C-CDA_Viewer#2]
Also, why is this completely different than the installer you can download from the intelsoft site?

How did this win?

**Comment by ScottBeeson** [comment]
C-CDA_Viewer-master/js/purejs.js net::ERR_FILE_NOT_FOUND

**Comment by ScottBeeson** [comment]
C-CDA_Viewer-master/cda.xsl. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

**Comment by brynlewis** [comment]
re XMLHttpRequest cannot load file - are you using chrome? As stated in the readme, chrome won't do a local transform without the user adjusting the security settings.

purejs.js is not needed, but I will remove the reference. Thanks for pointing it out.

The installer is the next version of the Viewer, running in a desktop app. It looks different because it has extra functionality.

You would have to ask the judges why it won - not being offensive may have helped.
